---
- name: "Creates BE directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive BE files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Dependencies"
  shell: |
    cd ~/backend-app
    npm install

- name: "Executing Node"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: echo msg
  debug:
    msg: "{{ execute_node.stdout_lines }}"

# - name: "Config pm2 to start as service"
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#     pm2 save